#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run1 "/control/execute run1.mac"
/gui/addButton run Original "/control/execute run_org.mac"
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "1 MeV"  "/gun/energy 1 MeV"
/gui/addButton gun "5 MeV"   "/gun/energy 5 MeV"
/gui/addButton gun "10 MeV"  "/gun/energy 10 MeV"
/gui/addButton gun "8Li"  "/gun/distributeLevel 2"
/gui/addButton gun "8Li + rand"  "/gun/distributeLevel 12"
/gui/addButton gun "90Sr"  "/gun/distributeLevel 3"
/gui/addButton gun "90Sr + random"     "/gun/distributeLevel 13"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"

#
# Field menu :
#/gui/addMenu field Field
#/gui/addButton field "off"       "/globalField/setValue 0   0 0 tesla"
#/gui/addButton field "0.2 tesla" "/globalField/setValue 0.2 0 0 tesla"
#/gui/addButton field "2.0 tesla" "/globalField/setValue 2.0 0 0 tesla"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
/gui/addButton viewer "Recreate" "/control/execute vis.mac"
/gui/addButton viewer "whiteBG" "/vis/viewer/set/background white"
#
